### ISSUE TITLE
Subtitles missing in breadcrumbs

### ISSUE THREAD

**Issue by gjtorikian** [github/open-source-guide#227]
![2017-02-13_11-35-46](https://cloud.githubusercontent.com/assets/64050/22900170/4361dafa-f1e2-11e6-8406-8eab2ea14d86.png)

Judging by the `/`, it seems like the page title wants to be in the breadcrumbs, but are missing instead.

**Comment by sotayamashita** [comment]
It will be good. 
@bkeepers What do you think ?
