### ISSUE TITLE
Self-referential anchors for headings misplaced

### ISSUE THREAD

**Issue by wooorm** [github/open-source-guide#240]
###### Steps to reproduce

1. Go to an article
2. Hover over heading
3. See funky placement of the hyperlink anchor icon thingy

<img width="514" alt="screen shot 2017-02-14 at 17 09 20" src="https://cloud.githubusercontent.com/assets/944406/22937347/9b80c6d2-f2d8-11e6-880b-2ad39407ada9.png">

**Comment by bkeepers** [comment]
Thanks for the bug report! What browser and operating system are you using?

**Comment by numrut** [comment]
The same happens in other WebKit-based browsers. Such as Midori and Epiphany.
