### ISSUE TITLE
blank space before "Contribute" link in header

### ISSUE THREAD

**Issue by matallo** [github/open-source-guide#244]
Links in the header are aligned with `display: inline-block` which creates a visual issue when hovering the link (see attached)

<img width="225" alt="screen shot 2017-02-14 at 17 53 30" src="https://cloud.githubusercontent.com/assets/36676/22939597/7e3d1f9c-f2df-11e6-94e7-cbd180f0457d.png">

This can be fixed applying a negative margin to the `<li>`, or changing the way the list items are aligned (i.e. floating the elements). Another workaround would be removing blank spaces between items.

**Comment by mlinksva** [comment]
@matallo I believe #259 is a fix in case you'd like to give feedback there.
