### ISSUE TITLE
no mention of free/libre?

### ISSUE THREAD

**Issue by omouse** [github/open-source-guide#250]
I like the mentions of GPL and AGPL but why no mention of free/libre and the four freedoms?

**Comment by mlinksva** [comment]
I suppose you're referring to the legal guide as that's mostly where various licenses are mentioned, including GPL. 

As the README says the guides document "how to run and contribute to an open source project". I'm not sure how using the words free/libre or describing the four freedoms contribute to that objective. In any case 1) those aren't legal issues, so mentions would go elsewhere and 2) feel free to make a concrete suggestion or even create an independent version using words you prefer. The material in the guides is open, and free/libre. :smile:

**Comment by mlinksva** [comment]
ps I've no idea whether it'd be a useful thing to note, but one "elsewhere" place could be https://opensource.guide/starting-a-project/#why-do-people-open-source-their-work -- ideology is one reason not mentioned.

**Comment by siguientepaso** [comment]
No logro ordenar las carpetas y la primera que busco es la de la memoria y nada!!
