### ISSUE TITLE
Tools to follow open-source metrics

### ISSUE THREAD

**Issue by Aurelsicoko** [github/open-source-guide#251]
Firstly, thanks for this amazing project! The open-source community needs a guide like that and I'm would be very honored to make my little contribution to it.

I'm working at a company called Strapi, and we are making OSS as well. To follow our open-source metrics, we developed a tool that provides a dashboard to keep an eye on differents metrics such as GitHub stars, npm downloads, Reddit mentions, etc, on a daily basis. We decided to pre-release it the last week and we asked people like @mxstbr, @Unitech or @hackjutsu to get feedback.

But when I saw the release of this guide, I was wondering our intern tool could be useful for the Open Source Metrics part because currently, it's quite difficult to see if a community is going well and if it's growing or not.

I put the link here: http://cometrics.strapi.io (it's completely free).

Would do make sense to submit a PR or making a list of useful tools for the Metrics part?

Thanks for your work!

**Comment by VincentGarreau** [comment]
l've been looking for this for a long time! Tracking the GitHub stars is very useful when you manage open source projects. Awesome 👍🏻

**Comment by hackjutsu** [comment]
I have been using **CoMetrics** for [one of my project](https://github.com/hackjutsu/Lepton) for a few days and provided feedbacks as mentioned by @Aurelsicoko. 

It's great to see how the number of stars and views changes everyday.  The missing part is I don't understand why the numbers change in this way, like why it got 125 stars one day but dropped to 32 the next day and then went up again.  I'm not sure what this means to the community.

@Aurelsicoko What's the repo link for **CoMetrics**?

**Comment by Aurelsicoko** [comment]
Thanks for your feedback! I don't think this is the right place to talk about the tool itself but the project isn't open-source for now. About the stars number, this is the purpose of CoMetrics to help you to determine why you have variations. In our case, we can precisely know the impact of a blog post or when we are doing a meetup in our community.

**Comment by nayafia** [comment]
Hi @Aurelsicoko! Thanks for the suggestion (and sorry for delayed reply, I've been on vacation).

CoMetrics looks like an awesome tool (thank you for making it!). However, we've added something to our policy, to manage incoming contributions better:

> don't add references or links to things you or your employer have created as others will do so if they appreciate it

I'm closing this issue as a result, but hopefully someone will add it if they find it useful. 😊

**Comment by Aurelsicoko** [comment]
Thank you @nayafia, I completely understand :)

**Comment by mxstbr** [comment]
That's a good policy 👏

**Comment by lutzhorn** [comment]
>  put the link here: http://cometrics.strapi.io (it's completely free).

I find nothing on this website about a license or ToS. The main site hosts http://strapi.io/terms and http://strapi.io/licenses:

> Strapi licenses Strapi software and provides related services through the "Services" pursuant to and in accordance with Strapi's then current Strapi Subscription Agreement found here http://strapi.io/licenses. Use of those Services may require you to open an account and register with Strapi pursuant to these Terms.

So the Strapi services are free to use but not Free as in Free Software. I vote against including a reference to a service like this.

**Comment by Aurelsicoko** [comment]
@lutzhorn We didn't take the time to make a proper website for CoMetrics but we are hosted CoMetrics as a subdomain because it was dedicated for an internal use only. So this is the why and how. We just opened this issue to share the tool but as I said we completely understand the position.
