### ISSUE TITLE
Expand options for UX designers

### ISSUE THREAD

**Issue by natdudley** [github/open-source-guide#267]
Not sure where this best lives, but it'd be excellent to see more projects do things like [Drupal's UX contribution requests](https://www.drupal.org/community-initiatives/drupal-core/usability) so that designers other than graphic designers who are new to OSS can see they are welcome and find how to contribute.

**Comment by joshsimmons** [comment]
That would be awesome. In a similar vein, I've just submitted a pull request to incorporate UX/UI into the How to Contribute guide. It's not perfect but I think it's an improvement: https://github.com/github/open-source-guide/pull/268/commits/944d6b9f232020a36167d82c46e3c8f3e17744bf

**Comment by mlinksva** [comment]
I merged https://github.com/github/open-source-guide/pull/268 as it's an immediately useful improvement. More discussion and PRs welcome. I can imagine ones:

* changing the language to excise code/non-code distinction (I see another issue for this #269 as I type...)
* further refinement of https://opensource.guide/how-to-contribute/#do-you-like-to-design
* work on https://opensource.guide/building-community/#meet-contributors-where-theyre-at ... an easy thing would be to just add another suggested label, a harder thing would be to distinguish between expertise-based and ~easy labels so it doesn't appear that non-programming-expertise-based ones are equivalent to ~easy.

**Comment by nayafia** [comment]
Hey @natdudley! It seems like #268 was a useful improvement. I also just added the Drupal example specifically in #345.

I'm going to close this issue as it seems it's been sufficiently addressed, but if anybody would like to tackle any of @mlinksva's suggestions above, or have ideas for other things they'd like to add, feel free to open a new issue or PR.
