### ISSUE TITLE
Remove code/not-code distinction

### ISSUE THREAD

**Issue by aurynn** [github/open-source-guide#269]
A large part of the conversation I've been having around this project (and #267 ties into this) is that the default framing of the guide is that code is a different kind of contribution than other contributions.

This distinction ties into the broader tech culture of positioning coding as _more important_ than other disciplines and skills, which means that the entire framing of the guide comes off as, you can contribute something useful, or maybe you can help with design or writing or something else.

It'd be great if the guide was able to position that code is only one of many skills, and possibly not even the most important skill in a project.

**Comment by lutzhorn** [comment]
@aurynn Your use of the word 'framing' sounds like you think this is done intentionally. As I am no native speaker, please tell me if I understand you correctly here. Thanks!

**Comment by aurynn** [comment]
@lutzhorn I don't think it was done intentionally, no. What I think is that it's the viewpoint that people in tech are taught is the primary and default viewpoint, and that it is generally unquestioned or unchallenged. 
Because it's the taught default, we end up with guides that are framed in that viewpoint, which is what I opened the issue to address. 😄

**Comment by nayafia** [comment]
Closing this issue in favor of #346. Additional feedback on that PR welcomed.
