### ISSUE TITLE
Ebook formats

### ISSUE THREAD

**Issue by sapegin** [github/open-source-guide#273]
Thanks for a great guide! I’ve just started reading it this morning and already love it ;-)

But it’s a bit long so having it an ebook format (epub, mobi) would be very helpful. What do you think about that?

The simplest solution would be [pandoc](http://pandoc.org/). There are some issues with HTML and formatting but in general it looks acceptable.

```
npm i -g replace
brew install pandoc

replace '\t?<img src="(.*?)"[^>]*>' '![]($1)' *.md
replace '</?(p|aside|div|label).*?>' ''
replace '  <input type="checkbox" id="cbox\d+" class="d-block float-left mt-1 mr-2" value="checkbox">\n  \n  ' '* '
replace ']\(/assets/' '](../assets/'

pandoc -S -o opensource.epub how-to-contribute.md starting-a-project.md finding-users.md building-community.md best-practices.md leadership-and-governance.md getting-paid.md code-of-conduct.md metrics.md legal.md
```

This requires some tweaking but it’s already something ;-) Let me know if should send a pull request.

**Comment by bkeepers** [comment]
> But it’s a bit long so having it an ebook format (epub, mobi) would be very helpful. What do you think about that?

Hey @sapegin, great suggestion!  I think it'd be great to have ebook versions.  It's not a high priority right now, but if you wanted to get a PR started, we could work on it!

**Comment by sapegin** [comment]
Awesome! I‘ll try to implement a basic script to generate epub and mobi and we‘ll see how we could integrate it.

**Comment by nayafia** [comment]
Closing this via #305. Additional ebook needs are being discussed in #316.
