### ISSUE TITLE
Good to have "scroll to top" button

### ISSUE THREAD

**Issue by daminisatya** [github/open-source-guide#274]
For longer posts, it's always a best UX to have "Scroll to top" button.

**Comment by daminisatya** [comment]
I would like to work on this, if the issue is marked as valid.

**Comment by sivadass** [comment]
+1

**Comment by sotayamashita** [comment]
@bkeepers  What do you think ?

**Comment by bkeepers** [comment]
I don't feel strongly either way. If someone submits a PR that is well designed an subtle, we'd consider merging it. I'm going to close this out in the mean time since this isn't something we're actively seeking, but feel free to open a PR.

**Comment by daminisatya** [comment]
@bkeepers Cool! Will work on it and send a PR.
