### ISSUE TITLE
Describe how to deal with false reports of CoC violations

### ISSUE THREAD

**Issue by lutzhorn** [github/open-source-guide#294]
The section about [Enforcing your code of conduct](https://opensource.guide/code-of-conduct/#enforcing-your-code-of-conduct) only makes sense if the report about a CoC violation is valid. But it may also happen that a report is false: the violation did not happen. The guide must mention what should be done in this case.

Right now the guide gives the impression that every CoC violation report is valid and it is only a question of how harsh to punish the accused person.

**Comment by CoralineAda** [comment]
There is a PR that adds content that hopefully addresses your concerns. You can comment [here](https://github.com/github/open-source-guide/pull/300)

**Comment by bkeepers** [comment]
Thanks @lutzhorn for bringing it up, and thanks @CoralineAda for the PR!

**Comment by DHADHIE** [comment]
What do u mean?

**Comment by lutzhorn** [comment]
@DHADHIE What in this ticket are you referring to? Whom do you ask?
