### ISSUE TITLE
Suggestion where to contribute

### ISSUE THREAD

**Issue by xtuc** [github/open-source-guide#303]
Lots of people want to contribute but don't know where.

I recently launched a service which aggregate issues for beginners: https://contributor.ninja.

Discussion on Twitter: https://twitter.com/svensauleau/status/823189011044806658

I would be happy to make a PR if this is accepted.

Thanks,
Sven.

**Comment by bkeepers** [comment]
Hey @xtuc, contributor.ninja looks good! We have some similar projects [listed in the guides](https://opensource.guide/how-to-contribute/#finding-a-project-to-contribute-to), so feel free to open a pull request to add your project to this list.

Also, just a heads up that we (the team at GitHub that worked on these guides) are _very_ interested  in these sites that match new contributors up with projects that are welcoming to newcomers. We'll likely be endorsing one of them and working with the maintainers and other teams at GitHub to improve it. We'll reach out when we're starting work on that (probably in the next month or so).

**Comment by xtuc** [comment]
Ok great, thanks for your answer.

I'm happy to discuss this further if you'd like to.

**Comment by anant90** [comment]
@bkeepers Sorry for being late to the party, but what do you think of http://c2oss.com - contribute2OSS aggregates open issues marked as bugs or enhancements in the public Github repositories you have starred or are a member of. I made this at some point last year for myself, and was wondering if I should open a pull request for adding this to docs. Thanks!

**Comment by theo-armour** [comment]
@anant90 

Thank you for efforts. Helping people track open issues is, heh heh, a big issue.

BTW, I am an outsider just like you. Some thoughts:

This issue is closed. It's always a good good idea to open a new issue rather than trying re-open a closed issue.

I had a quick look at contribute2OSS.  

I did not see a link to the source code on GitHub or to anywhere else. I did not see a license either.

It seems to me that if OSG is to support or link any project then the project better be really open source itself.

Also, again thinking out loud, I feel I trust projects created by GitHub organizations more than I trust individual user projects.

Theo

**Comment by anant90** [comment]
@theo-armour Thanks a lot for all the feedback and the double entendre - let me make the Github repo public, add an MIT License and a link to the Github repo and open a new issue :)

**Comment by xtuc** [comment]
@theo-armour

> It seems to me that if OSG is to support or link any project then the project better be really open source itself.

Contributor.ninja isn't open-source yet. I'm willing to do it in the future but currently it is still in development.

> Also, again thinking out loud, I feel I trust projects created by GitHub organizations more than I trust individual user projects.

I agree and as @bkeepers mentionned ealier, GitHub is interessed in this kind of websites. It would be great to have a dedicated page like the current trending one.

@anant90

> aggregates open issues marked as bugs or enhancements in the public Github repositories you have starred or are a member of

This looks to me the same as the GitHub watch list and notifications.

**Comment by bkeepers** [comment]
@anant90 c2oss looks good!  It's probably the best visual design of the various sites for contributing.

Since @xtuc's PR was merged we've added a policy against people adding links to their own projects, so if someone else thinks it's valuable and wants to add it, they're welcome to open a PR.
