### ISSUE TITLE
Styling: emoji's in blockquotes (with italics)

### ISSUE THREAD

**Issue by hzoo** [github/open-source-guide#308]
Dono if it's just me but while I was reading through the excellent https://opensource.guide/how-to-contribute guide (and other than those being too real)..

I was wondering if we might want to change the emoji styling if possible?

Now

<img width="679" alt="screen shot 2017-02-19 at 11 41 01 pm" src="https://cloud.githubusercontent.com/assets/588473/23112241/e6106c84-f6fc-11e6-936a-165babd3af1d.png">

Suggestion?

<img width="674" alt="screen shot 2017-02-19 at 11 40 50 pm" src="https://cloud.githubusercontent.com/assets/588473/23112244/e8defa52-f6fc-11e6-804d-8110beedf2fb.png">

**Comment by bkeepers** [comment]
I'm seeing that too. It's weird that emoji get italicized. I'm not sure if there's a way to prevent that, or if we have to restructure the content to avoid using a blockquote there.

Any suggestions?

**Comment by hzoo** [comment]
Styling isn't by strong suit 😄 

Since an emoji is text just like the rest there isn't an easy why to make it apply without it applying to the rest of the text other than wrapping the emoji or the other text in it's own span and applying a different style to it?

**Comment by hzoo** [comment]
<img width="1049" alt="screen shot 2017-02-20 at 10 54 13 am" src="https://cloud.githubusercontent.com/assets/588473/23132326/34b74a20-f75b-11e6-8d02-d3d5a79ac090.png">

Actually since the other text is an an `em` could do a hack like

```css
blockquote {
  font-style: normal;
  em {
    font-style: italic;
  }
}
```

**Comment by wooorm** [comment]
I don’t think italics is needed for the block-quotes, why not use a slightly lighter colour, like below?

> 😇 “X doesn’t happen when I do Y”
> 
> 😢 “X is broken! Please fix it.”

... and I was just about to post about the double italics but @hzoo mentioned that first 😄
