### ISSUE TITLE
About translations

### ISSUE THREAD

**Issue by aleen42** [github/open-source-guide#322]
Hello, I am a front-end developer from China, and I have always translated some articles into Chinese. Here I have found that this open source guides can be deliver widely by translating them into different languages. However, is there any guideline for this translating? For instance, to create a plan for translation and provide a apparent list of guides contributed by others with issues, so that we can easily grasp what we can translate.

Sincerely yours, aleen42.

**Comment by lee-dohm** [comment]
Investigation into providing translations and creating guidelines is ongoing in #295 and #299. You may want to subscribe there for updates. Since this request is a duplicate of those, I'm going to close this one.

Thanks for reaching out and offering to help!
