### ISSUE TITLE
Request of possibility Multi-language of the open-source-guide

### ISSUE THREAD

**Issue by Gotgot59** [github/open-source-guide#325]
Hello, 
I Rapidly look and read the document you build, i find it interesting and helpful to a lot of project.
It's a document who can help the administrator of software development  in their task.
But I'm French, and so i like to read in French, And people with who i thing work on my soft will discuss in French. I think German, Spanish too need to can read the document in their native language to help them understand the way of open source. 
Is it possible to create the translation of the doc ?

**Comment by Moc** [comment]
https://github.com/github/open-source-guide/issues/299

**Comment by Gotgot59** [comment]
It's seem they chose crowdin-sync or https://www.transifex.com/ because of compatibility difficulty of the Github page and Jekyll specification. #295 is useful too

**Comment by webknjaz** [comment]
This issue duplicates #288

**Comment by Gotgot59** [comment]
But for the moment, their no starting translation ? Or @webknjaz start one fork choosing a technology of translation for Ukrainian ?

**Comment by webknjaz** [comment]
@Gotgot59 the Ukrainian is a pilot translation, it's been decided to give forking approach a try and see if keeping translations in forks will work well.

Also @bkeepers pointed out that another [similar translation work is welcome](https://github.com/github/open-source-guide/issues/288#issuecomment-281137887), he is willing to create another ticket like #299 for that.
