### ISSUE TITLE
License change discussion seems counter intuitive to me

### ISSUE THREAD

**Issue by jimmierock** [github/open-source-guide#327]
Under Section 6, the discussion noted that starting with a more permissive license gives the owner more options later on. I.e., starting with MIT makes it easy to change to a copy-left.

This seems wrong.

When you start with a MIT, you essentially gave away all rights to your project. You can't really claim them back. The opposite seems true, starting with a copy-left or more restrictive license, but wanting to give more later.

Similar to the idea that once you gave someone a free CD, you can't really charge them for it. But if you charge someone for a CD, you can certainly return their money or give them an additional song for free.

**Comment by lutzhorn** [comment]
It is true that all contributions up to the license change are licensed under the first license (MIT). But you as the copyright owner can always change the license for *future* contributions.

So you are correct that you can't 'claim them back'. But you can say that for example the MIT license does only apply to the project up to a certain point and that from this point on it is GPL licensed.

If people don't like this license change, they can fork the project from before the license change and keep the first license.

**Comment by jimmierock** [comment]
Ah, that makes sense. 

But why would the previous license matter for changing future contributions? Wouldn't re-licensing future contributions essentially equivalent to licensing a new product? Assuming you are the original copyright owner of course. I understand that previous licenses have an effect on one's ability to license future contributions if you received the product under a restrictive license, in that case, you can't give away rights you don't have.

**Comment by mlinksva** [comment]
@lutzhorn is right. Take his second paragraph, and swap the positions of MIT and GPL. That doesn't work. One can start with a MIT project and switch the project to GPL at some point in the future, but not vice versa (without getting all copyright holders' permissions).

@jimmierock losing this as I don't think there's anything immediate to change in the guide, but feel free to discuss further, or open another issue or pull request if you or anyone has specific ideas for making the section more intuitive, and still correct. :smile:
