### ISSUE TITLE
Broken links in https://github.com/github/open-source-guide/blob/gh-pages/_articles/legal.md

### ISSUE THREAD

**Issue by theo-armour** [github/open-source-guide#332]
Broken links in https://github.com/github/open-source-guide/blob/gh-pages/_articles/legal.md

In section 'What does my company's legal team need to know?'

'A good example is [Rackspace's Model IP and Open Source Contribution Policy]( https://processmechanics.com/2015/07/23/a-model-ip-and-open-source-contribution-policy/ ).'

And 

— @vanl, "[A Model IP and Open Source Contribution Policy]( https://processmechanics.com/2015/07/23/a-model-ip-and-open-source-contribution-policy/ )'"

**Comment by bkeepers** [comment]
@vanl it looks like the URLs on your site recently changed. Any chance you're going to set up redirects for old URLs?
