### ISSUE TITLE
Questions regarding LICENSE page

### ISSUE THREAD

**Issue by theo-armour** [github/open-source-guide#337]
Here's the link:

https://github.com/github/open-source-guide/blob/gh-pages/LICENSE

## Lack of Copyright Notice
There appears to be no copyright notice on this page.

Compare with the following - all of which have copyright notices somewhere on the page 

* https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md
* https://github.com/github/gh-ost
* https://github.com/github/orchestrator/blob/master/LICENSE

## Combined Creative Commons Explanation and License May Be Confusing

The text on the LICENSE page appears to be a word for word copy of

https://creativecommons.org/licenses/by/4.0/legalcode

If you read this page you will note that it combines both an explanation of the license and the license itself.

It might be clearer to people if the page had just the license text and linked back to the original CC page with the full CC explanation.

## Software License

Where is it?

**Comment by mlinksva** [comment]
A copyright notice is not required. License notices are at https://github.com/github/open-source-guide/#licenses

The other repos you point at are using licenses that come in the form of a template. Many licenses (basically, the longer ones) aren't templates, and are intended to be used verbatim, with notices elsewhere, such as a README at the project level, or in file headers.

Closing as I don't think any change needs to be made, but feel free to continue to discuss if anything above doesn't make sense to you.

**Comment by surfmuggle** [comment]
At least our legal department (Germany) would prefer (or requires us) to provide a copyright information. In [341](https://github.com/github/opensource.guide/issues/341) is a link to [List of parties to international copyright agreements](https://en.wikipedia.org/wiki/List_of_parties_to_international_copyright_agreements) and [TRIPS - Agreement on Trade-Related Aspects of Intellectual Property Rights ](https://en.wikipedia.org/wiki/TRIPS_Agreement) is mentioned. 
But is unclear to me if this means that it is agreed that a copyright holder information is not needed?
