### ISSUE TITLE
Should the Open Source Guide include a copyright notice?

### ISSUE THREAD

**Issue by theo-armour** [github/open-source-guide#341]

**Comment by theo-armour** [comment]
This is a continuation of #337 

@mlinksva stated

>A copyright notice is not required.

I agree with this assertion.

See https://en.wikipedia.org/wiki/Copyright_notice

> U.S. law no longer requires the use of a copyright notice, although placing it on a work does confer certain benefits to the copyright holder. 
> Prior law did, however, require a notice, and the use of a notice is still relevant to the copyright status of older works.

And on a higher plane - especially given this is a project about freely sharing code - then knowledge should be free and copyright issues a thing of the past.

But even if a copyright notice is not required in the US, might it be good to have one anyway?

The Open Source Guide appears to want to help people around the world - and not just US peeps.
 
So even if a copyright notice is not currently required in the United States, you should also consider that the United Nations has 193 members - each of which can say and do what it wants regarding copyright.

Is there somewhere that states that all 193 members have agreed that no copyright notice is required?

Another thought is that many people have an uninformed understanding of copyright and license.

GitHub has been taking a very active role in helping people become more informed about intellectual property issues. A good example of this is the encouragement for you to to use a template to add a copyright notice and license whenever you create a new repo.

But it's not just GitHub. The Wikipedia article mentioned above includes a section titled: [Reasons to include an optional copyright notice ](
https://en.wikipedia.org/wiki/Copyright_notice#Reasons_to_include_an_optional_copyright_notice )

Let's look at it another way.

What do you think when you look at a website that has no copyright notice. I think 'Clueless Bozos!!!'

I think that if you do not include a copyright notice with the Open Source Guide and you want people to be aware that you are aware of intellectual property issues then you neeed a notice somewhere that says something like:

"This site does not have a copyright notice because as of the date of this writing the United States does not require a copyright notice in order to establish copyright. If you wish to contribute and you are doing so from outside the United States you should consult a lawyer as to the rights and obligations of establishing copyright in your jurisdiction."

***

Fingers crossed, one day it will be all open source and we will no longer have these issues. In the mean time this is short and sweet:

copyright © Open Source Guide authors

**Comment by mlinksva** [comment]
> Is there somewhere that states that all 193 members have agreed that no copyright notice is required?

Close, all [Berne and TRIPS signatories](https://en.wikipedia.org/wiki/List_of_parties_to_international_copyright_agreements) agree that formalities (of which copyright notice is one) aren't required. I've looked in the past for jurisdictions outside of this set that clearly have copyright law and require formalities and haven't found any research about this; probably because if they exist they are economically insignificant. Would love pointers out of curiosity.

(I think it'd be better if formalities were required for copyright, especially registration, but that's widely considered unobtainable due to the tangle of existing agreements.)

> What do you think when you look at a website that has no copyright notice. I think 'Clueless Bozos!!!'

Funny, I think about the opposite when I see the opposite: superfluous boilerplaters, but only escalating to bozos when the notice is inaccurate, as it often is (overstatement, non-existing entity, wrong entity).

> copyright © Open Source Guide authors

At least that's not wrong, if understood to include corporate authors. Since it's harmless and you present evidence it could result in some people thinking better of the project, I'll add to our notices page in a moment.

**Comment by kytrinyx** [comment]
> copyright © Open Source Guide authors

Does that mean that each author owns the copyright of their own words? If I submit a sentence to a guide, am I an author? Or is it the original author of the document?

**Comment by lutzhorn** [comment]
One sentence probably is not enough, there is something like Threshold of originality ("Schöpfungshöhe" in German).

**Comment by mlinksva** [comment]
@kytrinyx yes, but keep in mind the author may be corporate in the case of works for hire; at this point the vast majority of the content is copyright GitHub. No, not only the original author.

**Comment by theo-armour** [comment]
@kytrinyx 

**> Does that mean that each author owns the copyright of their own words? If I submit a sentence to a guide, am I an author? Or is it the original author of the document?**


Good question.

See: https://en.wikipedia.org/wiki/Threshold_of_originality << @lutzhorn 

Some thoughts:

Short phrases are not copyrightable

* https://www.copyright.gov/help/faq/faq-protect.html
    * See: How do I copyright a name, title, slogan, or logo?
* http://fairuse.stanford.edu/2003/09/09/copyright_protection_for_short/
    * Very, very long text on very short phrases - but a fun read.

Quotations are copyrightable, but usable according to fair use/fair dealing doctrines. < I don't yet have a good link for this assertion.

The Open Source Guide contains a good number of quotations along with images of the the authors of the quotations. I assume that most of these are not work for hire and are the copyright of the author.

***

IANAL, but I recommend that the Open Source Guide be considered as the work product over a lengthy period of time of many authors (alive or dead) residing in multiple jurisdictions - some contributing material as work-for-hire and others in their own right - ie anybody, any time, anywhere, for whatever reason.

**Comment by theo-armour** [comment]
> Should the Open Source Guide include a copyright notice?

@mlinksva 

Thank you for your gentle, informed and considered reply to my question.

I commend you on the decision at add a copyright notice to the Open Source Guide - but I can understand that you might have been done with a heavy heart.

So would it be possible to turn the inclusion into a learning opportunity?

How about adding under the notice a message something like the following?

> Please note that you no longer are required to add a copyright notice. Any significant textual material you create is automatically under copyright is most countries:
>* https://en.wikipedia.org/wiki/List_of_parties_to_international_copyright_agreements
>* https://en.wikipedia.org/wiki/Copyright_notice
> We do include a notice here because it is still safer to do so with projects of global intent.

Also how about setting a threshold for when a copyright notice is no longer needed?

* Google.con - no copyright notice
* Facebook,com - has copyright notice
* Microsoft.com - has copyright notice
* Apple.com - has copyright notice
* Amazon.com - has copyright notice

Let's say that when two or three out of five of the above have no copyright notice then _Open Source Guide_ can drop its notice.

**Comment by mlinksva** [comment]
Thanks @theo-armour. It'd be an interesting thing to turn the project legal notices into a learning tool. Just about everything could be annotated with an explanation of why it is. But that'd be a significant amount of work, likely not a good fit for this project, and I don't want to start down that road by adding just an explanation of copyright notices.
