### ISSUE TITLE
notices.md ~ link at bottom of page is broken

### ISSUE THREAD

**Issue by theo-armour** [github/open-source-guide#350]
notices.md ~ link at bottom of page is broken

> [Public speaking photo](../finding-users/#go-where-your-projects-audience-is-offline) used with permission of Zeeshaan Kaleem and released under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).

BTW, it would be use to know what image in the Guides this link refers to.

**Comment by mlinksva** [comment]
The link works on the website https://opensource.guide/notices/

As far as I know there's not a good way to make the link work in both places given the current structure of the site, other than by making the link in `notices.md` absolute. Maybe that is the right thing to do.

**Comment by theo-armour** [comment]
@mlinksva 

> As far as I know there's not a good way to make the link work in both places given the current structure of the site, other than by making the link in notices.md absolute.
> Maybe that is the right thing to do.

Thank you for catching that I came to this page from 

https://github.com/github/open-source-guide/blob/gh-pages/notices.md

> The link works on the website https://opensource.guide/notices/

Interesting. I've never seen this page.

How do you get to it from https://opensource.guide/ ?

**Comment by mlinksva** [comment]
https://github.com/github/open-source-guide/search?q=notices indicates it's linked from `_articles/legal` which is also served as https://opensource.guide/legal/ and `README.md` which is the "About" link on the website but is only served from the repo.

(`_config.yml` is where you can find which documents are served from a path other than the one they're at in the repo or are excluded from being served on the website.)

**Comment by bkeepers** [comment]
> As far as I know there's not a good way to make the link work in both places given the current structure of the site

#315 is trying to fix that. 🤞

**Comment by theo-armour** [comment]
@mlinksva 

Thank you for pointing out how easy it is to embed a GitHub search query in an issue.

May I suggest that the page in question be renamed:

From: notices.md
To: legal-disclaimer-and-notices.md

Also that the links in the README.md and https://opensource.guide/legal/ are gives as "Legal Disclaimer and Notices.

it's always a good thing for links and URLs be be very similar.

I can put in a pull request if you wish.

@bkeepers 

I hearted #315 several days ago

**Comment by mlinksva** [comment]
@theo-armour I'd rather not do that renaming. In the repo context, a file called `NOTICES` (of whatever case, with or without extension) is a convention, and in the web context, I prefer short but meaningful paths to URL SEO. But maybe I'm old fashioned. And I don't really care very much one way or the other.

I'm closing this as it seems the issue raised will be fixed when #315 ships and there's nothing independent of that to do. If there are other side issues such as file naming you wish to continue to discuss, feel free to add more comments or open a new issue or PR.
